#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppDrPhishel.Resource", IsApplication=true)]

namespace AppDrPhishel
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int BotonCrearCuenta = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int BotonRegresarCrear = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int EntryContraseña = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int EntryUsuario = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int botonCrearMain = 2131034130;
			
			// aapt resource value: 0x7f050003
			public const int entryApellido1Crear = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int entryApellido2Crear = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int entryCorreoCrear = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int entryDireccionCrear = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int entryNombreCrear = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int entryTelefonoCrear = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int entryUsuarioCrear = 2131034119;
			
			// aapt resource value: 0x7f050018
			public const int imageButton1 = 2131034136;
			
			// aapt resource value: 0x7f05000f
			public const int progressBarCrear = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int textApellido1Crear = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textApellido2Crear = 2131034116;
			
			// aapt resource value: 0x7f050016
			public const int textConstraseña = 2131034134;
			
			// aapt resource value: 0x7f050008
			public const int textCorreoCrear = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int textCrearCuenta = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int textDireccionCrear = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int textLogearCuenta = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int textNombreCrear = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int textTelefonoCrear = 2131034122;
			
			// aapt resource value: 0x7f050014
			public const int textUsuario = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int textUsuarioCrear = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CrearUsuarioLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int _apellido1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int _apellido2 = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int _application_name = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int _contraseña = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int _correo = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int _crear_cuenta = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int _crear_usuario = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int _direccion = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int _log_in = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int _nombre = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int _telefono = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int _usuario = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
