#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppDrPhishel.Resource", IsApplication=true)]

namespace AppDrPhishel
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CheckInicio = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DrPhi = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int IconoDoctor = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int IconoPaciente = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050012
			public const int CITASDOCTORLAYOUTlista = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int CREARCITACONFIRMARDOCTOR_BotonNO = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int CREARCITACONFIRMARDOCTOR_BotonSI = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int CREARCITALISTADOCTORES_lista = 2131034133;
			
			// aapt resource value: 0x7f05000e
			public const int CREARUSUARIO_BotonCrearCuenta = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int CREARUSUARIO_BotonRegresar = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int CREARUSUARIO_entryApellido1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int CREARUSUARIO_entryApellido2 = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int CREARUSUARIO_entryConstraseña = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int CREARUSUARIO_entryCorreo = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int CREARUSUARIO_entryDireccion = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int CREARUSUARIO_entryNombre = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int CREARUSUARIO_entryTelefono = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int CREARUSUARIO_entryUsuario = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int CREARUSUARIO_textApellido1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int CREARUSUARIO_textApellido2 = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int CREARUSUARIO_textContraseña = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int CREARUSUARIO_textCorreo = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int CREARUSUARIO_textDireccion = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int CREARUSUARIO_textTelefono = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int CREARUSUARIO_textUsuario = 2131034118;
			
			// aapt resource value: 0x7f050031
			public const int DOCTOR_BotonAgregarPaciente = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int DOCTOR_BotonCalendarioCitas = 2131034160;
			
			// aapt resource value: 0x7f05002f
			public const int DOCTOR_BotonHistorialPacientes = 2131034159;
			
			// aapt resource value: 0x7f050034
			public const int DOCTOR_botonRegresar = 2131034164;
			
			// aapt resource value: 0x7f050033
			public const int DOCTOR_textNombreUsuario = 2131034163;
			
			// aapt resource value: 0x7f050032
			public const int DOCTOR_textUsuario = 2131034162;
			
			// aapt resource value: 0x7f050017
			public const int HISTORIALPACIENTEUSUARIO_lista = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int HISTORIALPEDIDOSDOCTORlista = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int LISTVIEWCITASDOCTOR_textApellidoPaciente = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int LISTVIEWCITASDOCTOR_textDia = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int LISTVIEWCITASDOCTOR_textHora = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int LISTVIEWCITASDOCTOR_textNombrePaciente = 2131034136;
			
			// aapt resource value: 0x7f05001e
			public const int LISTVIEWHISTORIALUSUARIO_textDescripcion = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int LISTVIEWHISTORIALUSUARIO_textFecha = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int LISTVIEWHISTORIALUSUARIO_textNombreDoctor = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int LISTVIEWLISTADOCTORES_textApellido1 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int LISTVIEWLISTADOCTORES_textApellido2 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int LISTVIEWLISTADOCTORES_textEspecialidad = 2131034146;
			
			// aapt resource value: 0x7f05001f
			public const int LISTVIEWLISTADOCTORES_textNombreDoctor = 2131034143;
			
			// aapt resource value: 0x7f050024
			public const int LISTVIEWPACIENTEStextApellido1 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int LISTVIEWPACIENTEStextApellido2 = 2131034149;
			
			// aapt resource value: 0x7f050023
			public const int LISTVIEWPACIENTEStextNombre = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int LISTVIEWPACIENTEStextPadecimiento = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int MAIN_botonCrear = 2131034152;
			
			// aapt resource value: 0x7f05002e
			public const int MAIN_botonLogearse = 2131034158;
			
			// aapt resource value: 0x7f05002d
			public const int MAIN_entryContraseña = 2131034157;
			
			// aapt resource value: 0x7f05002b
			public const int MAIN_entryUsuario = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int MAIN_textConstraseña = 2131034156;
			
			// aapt resource value: 0x7f050029
			public const int MAIN_textCrearCuenta = 2131034153;
			
			// aapt resource value: 0x7f050027
			public const int MAIN_textLogearCuenta = 2131034151;
			
			// aapt resource value: 0x7f05002a
			public const int MAIN_textUsuario = 2131034154;
			
			// aapt resource value: 0x7f050036
			public const int USARIO_BotonCalendarioCitas = 2131034166;
			
			// aapt resource value: 0x7f050035
			public const int USUARIO_BotonHistorialPacientes = 2131034165;
			
			// aapt resource value: 0x7f050039
			public const int USUARIO_botonRegresar = 2131034169;
			
			// aapt resource value: 0x7f050038
			public const int USUARIO_textNombreUsuario = 2131034168;
			
			// aapt resource value: 0x7f050037
			public const int USUARIO_textUsuario = 2131034167;
			
			// aapt resource value: 0x7f050000
			public const int textNombreCREARUSUARIO = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AgregarPacienteDoctorLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CitasDoctorLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CrearCitaConfirmarDoctorLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CrearCitaListaDoctoresLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CrearUsuarioLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int HistorialPacienteDoctorLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int HistorialPacienteUsuarioLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ListViewTextFormatCitasDoctorLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListViewTextFormatHistorialPaciente = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ListViewTextFormatListaDoctoresCita = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ListViewTextFormatPacientesLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int VistaDoctorLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int VistaUsuarioLayout = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int _No = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int _Si = 2130968580;
			
			// aapt resource value: 0x7f040012
			public const int _agregar_cita = 2130968594;
			
			// aapt resource value: 0x7f04000f
			public const int _agregar_paciente = 2130968591;
			
			// aapt resource value: 0x7f040009
			public const int _apellido1 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int _apellido2 = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int _application_name = 2130968577;
			
			// aapt resource value: 0x7f040010
			public const int _calendario_citas = 2130968592;
			
			// aapt resource value: 0x7f040007
			public const int _contraseña = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int _correo = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int _crear_cuenta = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int _crear_usuario = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int _direccion = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int _historial = 2130968590;
			
			// aapt resource value: 0x7f040011
			public const int _historialpaciente = 2130968593;
			
			// aapt resource value: 0x7f040005
			public const int _log_in = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int _nombre = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int _telefono = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int _usuario = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
